name             'serverspec_test_helper'
maintainer       'Scott Carter'
maintainer_email 'scottcarter87@gmail.com'
license          'All rights reserved'
description      'Installs/Configures serverspec_test_helper'
long_description 'Installs/Configures serverspec_test_helper'
version          '0.1.0'
